version: "3"

services: 
    api:
        container_name: lapisco_chalenge_globo_fastapi_trainee
        command: "uvicorn app:app --reload --host 0.0.0.0 --port $PORT"
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:$PORT
        env_file: .env
        
        restart: always
